<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>false</IsPackable>
    <RootNamespace>KartChrono</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pure.Primitives" Version="3.6.5" />
    <PackageReference Include="Pure.Primitives.Abstractions" Version="4.3.0" />
    <PackageReference Include="Pure.Primitives.Number.Operations" Version="1.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KartChrono.Abstractions\KartChrono.Abstractions.csproj" />
  </ItemGroup>
</Project>
